    create table asset (
        id bigint generated by default as identity,
        asset_name varchar(255),
        customer_id bigint not null,
        size numeric(19,4) not null,
        usable_size numeric(19,4) not null,
        primary key (id)
    )

    create table customer (
        id bigint generated by default as identity,
        is_admin boolean not null,
        password varchar(255) not null,
        username varchar(255) not null,
        primary key (id)
    )

    create table orders (
        id bigint generated by default as identity,
        asset_name varchar(255),
        create_date timestamp(6),
        customer_id bigint not null,
        price numeric(19,4) not null,
        side varchar(255) check (side in ('BUY','SELL')),
        size numeric(19,4) not null,
        status varchar(255) check (status in ('PENDING','MATCHED','CANCELED')),
        primary key (id)
    )


    alter table if exists asset 
       add constraint idx_customer_asset unique (customer_id, asset_name)

    alter table if exists customer 
       add constraint UK_customer_username unique (username)

    create index idx_customer_date 
       on orders (customer_id, create_date)

    alter table if exists asset 
       add constraint FK_asset_customer 
       foreign key (customer_id) 
       references customer

    alter table if exists orders 
       add constraint FK_orders_customer 
       foreign key (customer_id) 
       references customer